---

- name: Ensure /opt/oulib/zabbix dirs exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: wheel
    recurse: yes
  with_items:
    - /opt/oulib/zabbix/bin
    - /opt/oulib/zabbix/etc

- name: scripts to /opt/oulib/zabbix/bin
  copy:
    src: "{{ item }}"
    dest: /opt/oulib/zabbix/bin/
    mode: 0755
    owner: root
    group: wheel
  with_items:
    - check_ldap.py

- name: secrets to /opt/oulib/zabbix/etc
  template:
    src: secrets.yml.j2
    dest: /opt/oulib/zabbix/etc/secrets.yml
    mode: 0600
    owner: root
    group: root

- name : Configure Zabbix Server
  template: 
    src: templates/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: zabbix
    mode: 0640
  notify: Restart Zabbix server
    

- name : Configure Zabbix Web
  template: 
    src: templates/zabbix.conf.j2
    dest:  /etc/httpd/conf.d/zabbix.conf
    owner: root
    group: zabbix
    mode: 0640
  notify: Restart Zabbix web

- name : Configure Zabbix PHP
  template: 
    src: templates/zabbix.conf.php.j2
    dest:  /etc/zabbix/web/zabbix.conf.php
    owner: apache
    group: apache
    mode: 0644
  notify: Restart Zabbix web
