---
- name: Zabbix official repository configured
  yum:
    name: http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
    state: present

- name: Zabbix server and web interface packages installed
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - zabbix-server-mysql
    - zabbix-web-mysql

