---
- name: Configure Zabbix official repository
  yum:
    name: http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
    state: present

- name: Install Zabbix server and web interface
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - zabbix-server-mysql
    - zabbix-web-mysql

#
# Create a database
#

#
# Load database schema
#
    
    

- name : Configure Zabbix Server
  template: 
    src: templates/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: zabbix
    mode: 0640



- name: Start Zabbix server
  service:
    name: zabbix-server
    state: started


- name : Configure Zabbix Web
  template: 
    src: templates/zabbix.conf.j2
    dest:  /etc/httpd/conf.d/zabbix.conf
    owner: root
    group: zabbix
    mode: 0640


- name: Resart web server for Zabbix 
  service:
    name: zabbix-server
    state: restarted
