---
# tasks file for OULibraries.zabbix

- include: selinux.yml
  become: true
  when: (((ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")) and (ansible_distribution_major_version == "7"))
  tags:
    - zabbix_selinux

- include: yum.yml
  become: true
  when: (((ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")) and (ansible_distribution_major_version == "7"))
  tags:
    - zabbix_yum

- include: db.yml
  become: true
  when: (((ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")) and (ansible_distribution_major_version == "7"))
  tags:
    - zabbix_database

- include: assets.yml
  become: true
  when: (((ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")) and (ansible_distribution_major_version == "7"))
  tags:
    - zabbix_assets
