---
# tasks file for OULibraries.zabbix

- include: yum.yml
  become: true
  tags:
    - zabbix_yum

- include: db.yml
  become: true
  tags:
    - zabbix_database

- include: assets.yml
  become: true
  tags:
    - zabbix_assets
