---
- name: Zabbix official repository configured
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm 
    state: present

- name: Zabbix server and web interface packages installed
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - zabbix-server-mysql
    - zabbix-web-mysql

- name: Yum packages for external checks
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-ldap

